Repository woowa-techcamp-2024/Team1-3K1K, pull requests merged in 2024-08, with the labels that each got.

#11 프로젝트 기본 세팅
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/pr-template.md
  src/main/java/camp/woowak/lab/customer/domain/.gitkeep
  src/main/java/camp/woowak/lab/customer/domain/Customer.java
  src/main/java/camp/woowak/lab/customer/repository/.gitkeep
  src/main/java/camp/woowak/lab/customer/service/.gitkeep
  src/main/java/camp/woowak/lab/infra/.gitkeep
  src/main/java/camp/woowak/lab/menu/domain/Menu.java
  src/main/java/camp/woowak/lab/menu/repository/.gitkeep
  src/main/java/camp/woowak/lab/menu/service/.gitkeep
  src/main/java/camp/woowak/lab/order/domain/Order.java
  src/main/java/camp/woowak/lab/order/repository/.gitkeep
  src/main/java/camp/woowak/lab/order/service/.gitkeep
  src/main/java/camp/woowak/lab/payaccount/domain/PayAccount.java
  src/main/java/camp/woowak/lab/payaccount/repository/.gitkeep
  src/main/java/camp/woowak/lab/payaccount/service/.gitkeep
  src/main/java/camp/woowak/lab/payment/domain/PointPayment.java
  src/main/java/camp/woowak/lab/payment/repository/.gitkeep
  src/main/java/camp/woowak/lab/payment/service/.gitkeep
  src/main/java/camp/woowak/lab/store/domain/Store.java
  src/main/java/camp/woowak/lab/store/repository/.gitkeep
  src/main/java/camp/woowak/lab/store/service/.gitkeep
  src/main/java/camp/woowak/lab/vendor/domain/Vendor.java
  src/main/java/camp/woowak/lab/vendor/repository/.gitkeep
  src/main/java/camp/woowak/lab/vendor/service/.gitkeep
  src/main/java/camp/woowak/lab/web/api/.gitkeep
  src/main/java/camp/woowak/lab/web/authentication/.gitkeep
  src/main/java/camp/woowak/lab/web/dao/.gitkeep
  src/main/java/camp/woowak/lab/web/dto/request/.gitkeep
  src/main/java/camp/woowak/lab/web/dto/response/.gitkeep
  src/main/java/camp/woowak/lab/web/filter/.gitkeep
  src/main/java/camp/woowak/lab/web/resolver/.gitkeep
  src/main/java/camp/woowak/lab/web/view/.gitkeep
Labels: ✨ Feature

#23 공통 응답 명세
  src/main/java/camp/woowak/lab/web/api/utils/APIResponse.java
  src/main/java/camp/woowak/lab/web/api/utils/APIUtils.java
  src/test/java/camp/woowak/lab/web/api/utils/APIUtilsTest.java
Labels: ✨ Feature, ⚙ Setting

#24 Exception 컨벤션
  src/main/java/camp/woowak/lab/common/advice/DomainExceptionHandler.java
  src/main/java/camp/woowak/lab/common/advice/GlobalExceptionHandler.java
  src/main/java/camp/woowak/lab/common/exception/BadRequestException.java
  src/main/java/camp/woowak/lab/common/exception/ConflictException.java
  src/main/java/camp/woowak/lab/common/exception/ErrorCode.java
  src/main/java/camp/woowak/lab/common/exception/ForbiddenException.java
  src/main/java/camp/woowak/lab/common/exception/HttpStatusException.java
  src/main/java/camp/woowak/lab/common/exception/MethodNotAllowedException.java
  src/main/java/camp/woowak/lab/common/exception/NotFoundException.java
  src/main/java/camp/woowak/lab/common/exception/UnauthorizedException.java
Labels: ✨ Feature, ⚙ Setting

#25 인증 인가
  src/main/java/camp/woowak/lab/common/exception/ErrorCode.java
  src/main/java/camp/woowak/lab/web/authentication/AuthenticationErrorCode.java
  src/main/java/camp/woowak/lab/web/authentication/LoginCustomer.java
  src/main/java/camp/woowak/lab/web/authentication/LoginMember.java
  src/main/java/camp/woowak/lab/web/authentication/LoginVendor.java
  src/main/java/camp/woowak/lab/web/authentication/annotation/AuthenticationPrincipal.java
  src/main/java/camp/woowak/lab/web/resolver/session/LoginMemberArgumentResolver.java
  src/main/java/camp/woowak/lab/web/resolver/session/SessionConst.java
  src/main/java/camp/woowak/lab/web/resolver/session/SessionCustomerArgumentResolver.java
  src/main/java/camp/woowak/lab/web/resolver/session/SessionVendorArgumentResolver.java
  src/test/java/camp/woowak/lab/web/resolver/session/SessionCustomerArgumentResolverTest.java
  src/test/java/camp/woowak/lab/web/resolver/session/SessionVendorArgumentResolverTest.java
Labels: ✨ Feature

#29 HttpStatusException 생성자 추가
  src/main/java/camp/woowak/lab/common/exception/HttpStatusException.java
Labels: ✨ Feature, ⚙ Setting

#12 점주 회원가입
  src/main/java/camp/woowak/lab/common/advice/GlobalExceptionHandler.java
  src/main/java/camp/woowak/lab/customer/domain/Customer.java
  src/main/java/camp/woowak/lab/menu/domain/Menu.java
  src/main/java/camp/woowak/lab/order/domain/Order.java
  src/main/java/camp/woowak/lab/payaccount/domain/PayAccount.java
  src/main/java/camp/woowak/lab/payaccount/repository/PayAccountRepository.java
  src/main/java/camp/woowak/lab/payment/domain/PointPayment.java
  src/main/java/camp/woowak/lab/store/domain/Store.java
  src/main/java/camp/woowak/lab/vendor/domain/Vendor.java
  src/main/java/camp/woowak/lab/vendor/domain/VendorValidator.java
  src/main/java/camp/woowak/lab/vendor/exception/DuplicateEmailException.java
  src/main/java/camp/woowak/lab/vendor/exception/InvalidVendorCreationException.java
  src/main/java/camp/woowak/lab/vendor/exception/VendorErrorCode.java
  src/main/java/camp/woowak/lab/vendor/repository/.gitkeep
  src/main/java/camp/woowak/lab/vendor/repository/VendorRepository.java
  src/main/java/camp/woowak/lab/vendor/service/.gitkeep
  src/main/java/camp/woowak/lab/vendor/service/SignUpVendorService.java
  src/main/java/camp/woowak/lab/vendor/service/command/SignUpVendorCommand.java
  src/main/java/camp/woowak/lab/web/api/.gitkeep
  src/main/java/camp/woowak/lab/web/api/vendor/VendorApiController.java
  src/main/java/camp/woowak/lab/web/api/vendor/VendorApiControllerAdvice.java
  src/main/java/camp/woowak/lab/web/authentication/.gitkeep
  src/main/java/camp/woowak/lab/web/authentication/NoOpPasswordEncoder.java
  src/main/java/camp/woowak/lab/web/authentication/PasswordEncoder.java
  src/main/java/camp/woowak/lab/web/authentication/config/AuthenticationConfig.java
  src/main/java/camp/woowak/lab/web/dto/request/.gitkeep
  src/main/java/camp/woowak/lab/web/dto/request/vendor/SignUpVendorRequest.java
  src/main/java/camp/woowak/lab/web/dto/response/.gitkeep
  src/main/java/camp/woowak/lab/web/dto/response/ApiResponse.java
  src/main/java/camp/woowak/lab/web/dto/response/vendor/SignUpVendorResponse.java
  src/main/java/camp/woowak/lab/web/error/ErrorCode.java
  src/main/java/camp/woowak/lab/web/validation/annotation/Phone.java
  src/main/java/camp/woowak/lab/web/validation/validator/PhoneNumberValidator.java
  src/main/resources/application.properties
  src/test/java/camp/woowak/lab/fixture/VendorFixture.java
  src/test/java/camp/woowak/lab/payaccount/domain/TestPayAccount.java
  src/test/java/camp/woowak/lab/vendor/domain/VendorTest.java
  src/test/java/camp/woowak/lab/vendor/repository/VendorRepositoryTest.java
  src/test/java/camp/woowak/lab/vendor/service/SignUpVendorServiceTest.java
  src/test/java/camp/woowak/lab/web/api/VendorApiControllerTest.java
Labels: ✨ Feature

#16 구매자 회원가입
  src/main/java/camp/woowak/lab/common/exception/BadRequestException.java
  src/main/java/camp/woowak/lab/customer/domain/.gitkeep
  src/main/java/camp/woowak/lab/customer/domain/Customer.java
  src/main/java/camp/woowak/lab/customer/domain/CustomerValidator.java
  src/main/java/camp/woowak/lab/customer/exception/CustomerErrorCode.java
  src/main/java/camp/woowak/lab/customer/exception/DuplicateEmailException.java
  src/main/java/camp/woowak/lab/customer/exception/InvalidCreationException.java
  src/main/java/camp/woowak/lab/customer/repository/.gitkeep
  src/main/java/camp/woowak/lab/customer/repository/CustomerRepository.java
  src/main/java/camp/woowak/lab/customer/service/.gitkeep
  src/main/java/camp/woowak/lab/customer/service/SignUpCustomerService.java
  src/main/java/camp/woowak/lab/customer/service/command/SignUpCustomerCommand.java
  src/main/java/camp/woowak/lab/web/api/customer/CustomerApiController.java
  src/main/java/camp/woowak/lab/web/api/customer/CustomerExceptionHandler.java
  src/main/java/camp/woowak/lab/web/dto/request/SignUpVendorRequest.java
  src/main/java/camp/woowak/lab/web/dto/request/customer/SignUpCustomerRequest.java
  src/main/java/camp/woowak/lab/web/dto/response/customer/SignUpCustomerResponse.java
  src/test/java/camp/woowak/lab/customer/domain/CustomerTest.java
  src/test/java/camp/woowak/lab/customer/service/SignUpCustomerServiceIntegrationTest.java
  src/test/java/camp/woowak/lab/customer/service/SignUpCustomerServiceTest.java
  src/test/java/camp/woowak/lab/fixture/CustomerFixture.java
  src/test/java/camp/woowak/lab/web/api/customer/CustomerApiControllerTest.java
Labels: ✨ Feature

#35 GlobalExceptionHandler 응답 방식 수정
  src/main/java/camp/woowak/lab/common/advice/GlobalExceptionHandler.java
Labels: ✨ Feature, ⚙ Setting, 🔨 Refactor

#15 구매자 페이먼트 충전
  src/main/java/camp/woowak/lab/LabApplication.java
  src/main/java/camp/woowak/lab/customer/domain/Customer.java
  src/main/java/camp/woowak/lab/payaccount/domain/AccountTransactionType.java
  src/main/java/camp/woowak/lab/payaccount/domain/PayAccount.java
  src/main/java/camp/woowak/lab/payaccount/domain/PayAccountHistory.java
  src/main/java/camp/woowak/lab/payaccount/exception/DailyLimitExceededException.java
  src/main/java/camp/woowak/lab/payaccount/exception/InsufficientBalanceException.java
  src/main/java/camp/woowak/lab/payaccount/exception/InvalidTransactionAmountException.java
  src/main/java/camp/woowak/lab/payaccount/exception/NotFoundAccountException.java
  src/main/java/camp/woowak/lab/payaccount/exception/PayAccountErrorCode.java
  src/main/java/camp/woowak/lab/payaccount/repository/.gitkeep
  src/main/java/camp/woowak/lab/payaccount/repository/PayAccountHistoryRepository.java
  src/main/java/camp/woowak/lab/payaccount/repository/PayAccountRepository.java
  src/main/java/camp/woowak/lab/payaccount/service/.gitkeep
  src/main/java/camp/woowak/lab/payaccount/service/PayAccountChargeService.java
  src/main/java/camp/woowak/lab/payaccount/service/command/PayAccountChargeCommand.java
  src/main/java/camp/woowak/lab/web/api/payaccount/PayAccountApiController.java
  src/main/java/camp/woowak/lab/web/api/payaccount/PayAccountApiControllerAdvice.java
  src/main/java/camp/woowak/lab/web/config/WebConfig.java
  src/main/java/camp/woowak/lab/web/dto/request/payaccount/PayAccountChargeRequest.java
  src/main/java/camp/woowak/lab/web/dto/response/payaccount/PayAccountChargeResponse.java
  src/main/java/camp/woowak/lab/web/resolver/session/SessionCustomerArgumentResolver.java
  src/main/java/camp/woowak/lab/web/resolver/session/SessionVendorArgumentResolver.java
  src/test/java/camp/woowak/lab/payaccount/domain/PayAccountTest.java
  src/test/java/camp/woowak/lab/payaccount/service/PayAccountChargeServiceTest.java
  src/test/java/camp/woowak/lab/web/api/PayAccountApiControllerTest.java
Labels: ✨ Feature

#18 점주 가게 등록
  src/main/java/camp/woowak/lab/customer/domain/CustomerValidator.java
  src/main/java/camp/woowak/lab/customer/service/SignUpCustomerService.java
  src/main/java/camp/woowak/lab/infra/config/InfraConfiguration.java
  src/main/java/camp/woowak/lab/infra/date/CurrentDateTime.java
  src/main/java/camp/woowak/lab/infra/date/DateTimeProvider.java
  src/main/java/camp/woowak/lab/payaccount/exception/PayAccountErrorCode.java
  src/main/java/camp/woowak/lab/store/domain/Store.java
  src/main/java/camp/woowak/lab/store/domain/StoreAddress.java
  src/main/java/camp/woowak/lab/store/domain/StoreCategory.java
  src/main/java/camp/woowak/lab/store/domain/StoreTime.java
  src/main/java/camp/woowak/lab/store/domain/StoreValidator.java
  src/main/java/camp/woowak/lab/store/exception/StoreException.java
  src/main/java/camp/woowak/lab/store/repository/StoreCategoryRepository.java
  src/main/java/camp/woowak/lab/store/repository/StoreRepository.java
  src/main/java/camp/woowak/lab/store/service/StoreRegistrationService.java
  src/main/java/camp/woowak/lab/store/service/dto/StoreRegistrationRequest.java
  src/main/java/camp/woowak/lab/vendor/repository/VendorRepository.java
  src/main/java/camp/woowak/lab/web/api/customer/CustomerApiController.java
  src/main/java/camp/woowak/lab/web/api/store/StoreApiController.java
  src/main/java/camp/woowak/lab/web/api/store/StoreExceptionHandler.java
  src/main/java/camp/woowak/lab/web/resolver/session/SessionCustomerArgumentResolver.java
  src/main/java/camp/woowak/lab/web/resolver/session/SessionVendorArgumentResolver.java
  src/main/resources/application.properties
  src/main/resources/application.yaml
  src/test/java/camp/woowak/lab/infra/time/FixedDateTime.java
  src/test/java/camp/woowak/lab/store/domain/StoreTest.java
  src/test/java/camp/woowak/lab/store/repository/StoreCategoryRepositoryTest.java
  src/test/java/camp/woowak/lab/store/repository/StoreRepositoryTest.java
  src/test/java/camp/woowak/lab/store/service/StoreRegistrationServiceTest.java
  src/test/java/camp/woowak/lab/web/api/store/StoreApiControllerTest.java
Labels: ✨ Feature

#50 [ feat] 컨트롤러 API 공통 응답 처리
  src/main/java/camp/woowak/lab/web/advice/APIResponseAdvice.java
  src/main/java/camp/woowak/lab/web/api/customer/CustomerApiController.java
  src/main/java/camp/woowak/lab/web/api/payaccount/PayAccountApiController.java
  src/main/java/camp/woowak/lab/web/api/store/StoreApiController.java
  src/main/java/camp/woowak/lab/web/api/utils/APIResponse.java
  src/main/java/camp/woowak/lab/web/api/utils/APIUtils.java
  src/main/java/camp/woowak/lab/web/api/vendor/VendorApiController.java
  src/test/java/camp/woowak/lab/web/advice/APIResponseAdviceTest.java
Labels: ✨ Feature, ⚙ Setting

#57 [refactor] Payaccount CustomException 수정
  src/main/java/camp/woowak/lab/common/exception/NotFoundException.java
  src/main/java/camp/woowak/lab/payaccount/domain/PayAccount.java
  src/main/java/camp/woowak/lab/payaccount/exception/DailyLimitExceededException.java
  src/main/java/camp/woowak/lab/payaccount/exception/InsufficientBalanceException.java
  src/main/java/camp/woowak/lab/payaccount/exception/InvalidTransactionAmountException.java
  src/main/java/camp/woowak/lab/payaccount/exception/NotFoundAccountException.java
  src/main/java/camp/woowak/lab/payaccount/service/PayAccountChargeService.java
Labels: 🔨 Refactor

#58 [feat] Customer id 변경
  src/main/java/camp/woowak/lab/customer/domain/Customer.java
  src/main/java/camp/woowak/lab/customer/service/SignUpCustomerService.java
  src/main/java/camp/woowak/lab/payaccount/repository/PayAccountRepository.java
  src/main/java/camp/woowak/lab/payaccount/service/command/PayAccountChargeCommand.java
  src/main/java/camp/woowak/lab/web/api/customer/CustomerApiController.java
  src/main/java/camp/woowak/lab/web/authentication/LoginCustomer.java
  src/main/java/camp/woowak/lab/web/dto/response/customer/SignUpCustomerResponse.java
  src/test/java/camp/woowak/lab/customer/service/SignUpCustomerServiceIntegrationTest.java
  src/test/java/camp/woowak/lab/customer/service/SignUpCustomerServiceTest.java
  src/test/java/camp/woowak/lab/payaccount/service/PayAccountChargeServiceTest.java
  src/test/java/camp/woowak/lab/web/api/PayAccountApiControllerTest.java
  src/test/java/camp/woowak/lab/web/api/customer/CustomerApiControllerTest.java
Labels: ✨ Feature

#64 [feat] 구매자 로그인
  src/main/java/camp/woowak/lab/common/exception/UnauthorizedException.java
  src/main/java/camp/woowak/lab/customer/domain/Customer.java
  src/main/java/camp/woowak/lab/customer/exception/CustomerAuthenticationException.java
  src/main/java/camp/woowak/lab/customer/exception/CustomerErrorCode.java
  src/main/java/camp/woowak/lab/customer/repository/CustomerRepository.java
  src/main/java/camp/woowak/lab/customer/service/SignInCustomerService.java
  src/main/java/camp/woowak/lab/customer/service/command/SignInCustomerCommand.java
  src/main/java/camp/woowak/lab/web/api/customer/CustomerApiController.java
  src/main/java/camp/woowak/lab/web/api/customer/CustomerExceptionHandler.java
  src/main/java/camp/woowak/lab/web/dto/request/customer/SignInCustomerRequest.java
  src/main/java/camp/woowak/lab/web/dto/response/customer/SignInCustomerResponse.java
  src/main/java/camp/woowak/lab/web/error/ErrorCode.java
  src/test/java/camp/woowak/lab/customer/service/SignInCustomerServiceTest.java
  src/test/java/camp/woowak/lab/fixture/CustomerFixture.java
  src/test/java/camp/woowak/lab/web/api/customer/CustomerApiControllerTest.java
Labels: ✨ Feature

#65 [feat] 장바구니 담기 구현
  src/main/java/camp/woowak/lab/cart/domain/Cart.java
  src/main/java/camp/woowak/lab/cart/exception/CartErrorCode.java
  src/main/java/camp/woowak/lab/cart/exception/MenuNotFoundException.java
  src/main/java/camp/woowak/lab/cart/exception/OtherStoreMenuException.java
  src/main/java/camp/woowak/lab/cart/exception/StoreNotOpenException.java
  src/main/java/camp/woowak/lab/cart/repository/CartRepository.java
  src/main/java/camp/woowak/lab/cart/repository/InMemoryCartRepository.java
  src/main/java/camp/woowak/lab/cart/service/CartService.java
  src/main/java/camp/woowak/lab/cart/service/command/AddCartCommand.java
  src/main/java/camp/woowak/lab/menu/domain/Menu.java
  src/main/java/camp/woowak/lab/menu/repository/MenuRepository.java
  src/main/java/camp/woowak/lab/store/domain/Store.java
  src/main/java/camp/woowak/lab/store/domain/StoreTime.java
  src/main/java/camp/woowak/lab/web/api/cart/CartApiController.java
  src/main/java/camp/woowak/lab/web/api/cart/CartApiControllerAdvice.java
  src/main/java/camp/woowak/lab/web/dto/request/cart/AddCartRequest.java
  src/main/java/camp/woowak/lab/web/dto/response/cart/AddCartResponse.java
  src/test/java/camp/woowak/lab/cart/repository/InMemoryCartRepositoryTest.java
  src/test/java/camp/woowak/lab/cart/service/CartServiceTest.java
  src/test/java/camp/woowak/lab/web/api/cart/CartApiControllerTest.java
Labels: ✨ Feature

#67 [feat] 점주는 음식 카테고리를 등록할 수 있다
  src/main/java/camp/woowak/lab/common/advice/GlobalExceptionHandler.java
  src/main/java/camp/woowak/lab/common/exception/BadRequestException.java
  src/main/java/camp/woowak/lab/common/exception/ConflictException.java
  src/main/java/camp/woowak/lab/common/exception/ForbiddenException.java
  src/main/java/camp/woowak/lab/common/exception/MethodNotAllowedException.java
  src/main/java/camp/woowak/lab/common/exception/NotFoundException.java
  src/main/java/camp/woowak/lab/common/exception/UnauthorizedException.java
  src/main/java/camp/woowak/lab/menu/domain/MenuCategory.java
  src/main/java/camp/woowak/lab/menu/exception/DuplicateMenuCategoryException.java
  src/main/java/camp/woowak/lab/menu/exception/MenuErrorCode.java
  src/main/java/camp/woowak/lab/menu/exception/UnauthorizedMenuCategoryCreationException.java
  src/main/java/camp/woowak/lab/menu/service/.gitkeep
  src/main/java/camp/woowak/lab/menu/service/MenuCategoryRegistrationService.java
  src/main/java/camp/woowak/lab/menu/service/command/MenuCategoryRegistrationCommand.java
  src/main/java/camp/woowak/lab/store/domain/Store.java
  src/main/java/camp/woowak/lab/web/api/store/StoreApiController.java
  src/main/java/camp/woowak/lab/web/api/store/StoreExceptionHandler.java
  src/main/java/camp/woowak/lab/web/dto/request/store/MenuCategoryRegistrationRequest.java
  src/main/java/camp/woowak/lab/web/dto/response/store/MenuCategoryRegistrationResponse.java
  src/main/java/camp/woowak/lab/web/resolver/session/SessionVendorArgumentResolver.java
  src/test/java/camp/woowak/lab/fixture/MenuFixture.java
  src/test/java/camp/woowak/lab/menu/TestMenuCategory.java
  src/test/java/camp/woowak/lab/menu/repository/MenuCategoryRepositoryTest.java
  src/test/java/camp/woowak/lab/menu/service/MenuCategoryRegistrationServiceTest.java
  src/test/java/camp/woowak/lab/store/TestStore.java
  src/test/java/camp/woowak/lab/web/api/store/StoreApiControllerTest.java
Labels: ✨ Feature

#68 [refactor] 코드 스타일 통일
  src/main/java/camp/woowak/lab/menu/domain/Menu.java
  src/main/java/camp/woowak/lab/menu/domain/MenuCategoryValidator.java
  src/main/java/camp/woowak/lab/menu/domain/MenuValidator.java
  src/main/java/camp/woowak/lab/menu/exception/InvalidMenuCategoryCreationException.java
  src/main/java/camp/woowak/lab/menu/exception/InvalidMenuCreationException.java
  src/main/java/camp/woowak/lab/menu/exception/MenuErrorCode.java
  src/main/java/camp/woowak/lab/menu/exception/NotFoundMenuCategoryException.java
  src/main/java/camp/woowak/lab/store/domain/StoreValidator.java
  src/main/java/camp/woowak/lab/store/exception/InvalidStoreCreationException.java
  src/main/java/camp/woowak/lab/store/exception/NotEqualsOwnerException.java
  src/main/java/camp/woowak/lab/store/exception/NotFoundStoreCategoryException.java
  src/main/java/camp/woowak/lab/store/exception/NotFoundStoreException.java
  src/main/java/camp/woowak/lab/store/exception/StoreErrorCode.java
  src/main/java/camp/woowak/lab/store/exception/StoreException.java
  src/main/java/camp/woowak/lab/store/service/StoreMenuRegistrationService.java
  src/main/java/camp/woowak/lab/store/service/StoreRegistrationService.java
  src/main/java/camp/woowak/lab/store/service/command/MenuLineItem.java
  src/main/java/camp/woowak/lab/store/service/command/StoreMenuRegistrationCommand.java
  src/main/java/camp/woowak/lab/store/service/command/StoreRegistrationCommand.java
  src/main/java/camp/woowak/lab/store/service/dto/StoreMenuRegistrationRequest.java
  src/main/java/camp/woowak/lab/web/api/store/StoreApiController.java
  src/main/java/camp/woowak/lab/web/api/store/StoreExceptionHandler.java
  src/main/java/camp/woowak/lab/web/dto/request/store/StoreMenuRegistrationRequest.java
  src/main/java/camp/woowak/lab/web/dto/request/store/StoreRegistrationRequest.java
  src/main/java/camp/woowak/lab/web/dto/response/store/StoreMenuRegistrationResponse.java
  src/main/java/camp/woowak/lab/web/dto/response/store/StoreRegistrationResponse.java
  src/test/java/camp/woowak/lab/store/domain/StoreTest.java
  src/test/java/camp/woowak/lab/store/service/StoreMenuRegistrationServiceTest.java
  src/test/java/camp/woowak/lab/store/service/StoreRegistrationServiceTest.java
  src/test/java/camp/woowak/lab/web/api/store/StoreApiControllerTest.java
Labels: 🔨 Refactor

#71 [feat] 할인 쿠폰 등록
  src/main/java/camp/woowak/lab/coupon/domain/Coupon.java
  src/main/java/camp/woowak/lab/coupon/domain/CouponValidator.java
  src/main/java/camp/woowak/lab/coupon/exception/CouponErrorCode.java
  src/main/java/camp/woowak/lab/coupon/exception/DuplicateCouponTitleException.java
  src/main/java/camp/woowak/lab/coupon/exception/InvalidCreationCouponException.java
  src/main/java/camp/woowak/lab/coupon/repository/CouponRepository.java
  src/main/java/camp/woowak/lab/coupon/service/CreateCouponService.java
  src/main/java/camp/woowak/lab/coupon/service/command/CreateCouponCommand.java
  src/main/java/camp/woowak/lab/web/api/coupon/CouponApiController.java
  src/main/java/camp/woowak/lab/web/api/coupon/CouponExceptionHandler.java
  src/main/java/camp/woowak/lab/web/api/customer/CustomerExceptionHandler.java
  src/main/java/camp/woowak/lab/web/dto/request/coupon/CreateCouponRequest.java
  src/main/java/camp/woowak/lab/web/dto/response/coupon/CreateCouponResponse.java
  src/test/java/camp/woowak/lab/coupon/domain/CouponTest.java
  src/test/java/camp/woowak/lab/coupon/domain/TestCoupon.java
  src/test/java/camp/woowak/lab/coupon/service/CreateCouponServiceIntegrationTest.java
  src/test/java/camp/woowak/lab/coupon/service/CreateCouponServiceTest.java
  src/test/java/camp/woowak/lab/fixture/CouponFixture.java
  src/test/java/camp/woowak/lab/web/api/coupon/CouponApiControllerTest.java
Labels: ✨ Feature

#70 [feat] 장바구니에 현재까지 담은 음식 상품의 금액을 볼 수 있는 기능 추가
  src/main/java/camp/woowak/lab/cart/domain/Cart.java
  src/main/java/camp/woowak/lab/cart/service/CartService.java
  src/main/java/camp/woowak/lab/cart/service/command/CartTotalPriceCommand.java
  src/main/java/camp/woowak/lab/web/api/cart/CartApiController.java
  src/main/java/camp/woowak/lab/web/dto/response/cart/CartTotalPriceResponse.java
  src/test/java/camp/woowak/lab/cart/domain/CartTest.java
  src/test/java/camp/woowak/lab/cart/service/CartServiceTest.java
  src/test/java/camp/woowak/lab/fixture/CartFixture.java
  src/test/java/camp/woowak/lab/menu/TestMenu.java
  src/test/java/camp/woowak/lab/store/TestStore.java
  src/test/java/camp/woowak/lab/web/api/cart/CartApiControllerTest.java
Labels: ✨ Feature

#76 [feat] 음식 상품 수량 등록
  src/main/java/camp/woowak/lab/menu/domain/Menu.java
  src/main/java/camp/woowak/lab/menu/domain/MenuValidator.java
  src/main/java/camp/woowak/lab/menu/exception/MenuErrorCode.java
  src/main/java/camp/woowak/lab/store/service/StoreMenuRegistrationService.java
  src/main/java/camp/woowak/lab/store/service/command/MenuLineItem.java
  src/test/java/camp/woowak/lab/cart/service/CartServiceTest.java
  src/test/java/camp/woowak/lab/menu/TestMenu.java
  src/test/java/camp/woowak/lab/menu/domain/MenuTest.java
  src/test/java/camp/woowak/lab/store/service/StoreMenuRegistrationServiceTest.java
  src/test/java/camp/woowak/lab/web/api/cart/CartApiControllerTest.java
Labels: ✨ Feature

#82 [feat] 할인 쿠폰 발급
  src/main/java/camp/woowak/lab/coupon/domain/Coupon.java
  src/main/java/camp/woowak/lab/coupon/domain/CouponIssuance.java
  src/main/java/camp/woowak/lab/coupon/domain/CouponIssuanceValidator.java
  src/main/java/camp/woowak/lab/coupon/exception/CouponErrorCode.java
  src/main/java/camp/woowak/lab/coupon/exception/CouponIssuanceErrorCode.java
  src/main/java/camp/woowak/lab/coupon/exception/DuplicateCouponTitleException.java
  src/main/java/camp/woowak/lab/coupon/exception/ExpiredCouponException.java
  src/main/java/camp/woowak/lab/coupon/exception/InsufficientCouponQuantityException.java
  src/main/java/camp/woowak/lab/coupon/exception/InvalidICreationIssuanceException.java
  src/main/java/camp/woowak/lab/coupon/repository/CouponIssuanceRepository.java
  src/main/java/camp/woowak/lab/coupon/repository/CouponRepository.java
  src/main/java/camp/woowak/lab/coupon/service/IssueCouponService.java
  src/main/java/camp/woowak/lab/coupon/service/command/IssueCouponCommand.java
  src/main/java/camp/woowak/lab/customer/repository/CustomerRepository.java
  src/main/java/camp/woowak/lab/web/api/coupon/CouponApiController.java
  src/main/java/camp/woowak/lab/web/api/coupon/CouponExceptionHandler.java
  src/main/java/camp/woowak/lab/web/dto/response/coupon/IssueCouponResponse.java
  src/test/java/camp/woowak/lab/coupon/domain/CouponIssuanceTest.java
  src/test/java/camp/woowak/lab/coupon/domain/TestCoupon.java
  src/test/java/camp/woowak/lab/coupon/domain/TestCouponIssuance.java
  src/test/java/camp/woowak/lab/coupon/service/IssueCouponServiceIntegrationTest.java
  src/test/java/camp/woowak/lab/coupon/service/IssueCouponServiceTest.java
  src/test/java/camp/woowak/lab/customer/domain/TestCustomer.java
  src/test/java/camp/woowak/lab/fixture/CouponFixture.java
  src/test/java/camp/woowak/lab/fixture/CouponIssuanceFixture.java
  src/test/java/camp/woowak/lab/fixture/CustomerFixture.java
  src/test/java/camp/woowak/lab/web/api/coupon/CouponApiControllerTest.java
Labels: ✨ Feature

#98 [feat] querydsl을 설정하여 동적쿼리를 생성할 수 있다
  .gitignore
  build.gradle
  src/main/java/camp/woowak/lab/web/config/QuerydslConfig.java
Labels: 📃 Docs, ✨ Feature

#80 [feat] 구매자는 장바구니에 담긴 상품을 주문할 수 있다
  src/main/java/camp/woowak/lab/cart/domain/Cart.java
  src/main/java/camp/woowak/lab/cart/domain/vo/CartItem.java
  src/main/java/camp/woowak/lab/cart/exception/CartErrorCode.java
  src/main/java/camp/woowak/lab/cart/service/CartService.java
  src/main/java/camp/woowak/lab/customer/exception/CustomerErrorCode.java
  src/main/java/camp/woowak/lab/customer/exception/NotFoundCustomerException.java
  src/main/java/camp/woowak/lab/customer/repository/CustomerRepository.java
  src/main/java/camp/woowak/lab/menu/domain/Menu.java
  src/main/java/camp/woowak/lab/menu/exception/MenuErrorCode.java
  src/main/java/camp/woowak/lab/menu/exception/NotEnoughStockException.java
  src/main/java/camp/woowak/lab/menu/repository/MenuRepository.java
  src/main/java/camp/woowak/lab/order/domain/Order.java
  src/main/java/camp/woowak/lab/order/domain/PriceChecker.java
  src/main/java/camp/woowak/lab/order/domain/SingleStoreOrderValidator.java
  src/main/java/camp/woowak/lab/order/domain/StockRequester.java
  src/main/java/camp/woowak/lab/order/domain/WithdrawPointService.java
  src/main/java/camp/woowak/lab/order/domain/vo/OrderItem.java
  src/main/java/camp/woowak/lab/order/exception/EmptyCartException.java
  src/main/java/camp/woowak/lab/order/exception/MinimumOrderPriceNotMetException.java
  src/main/java/camp/woowak/lab/order/exception/MultiStoreOrderException.java
  src/main/java/camp/woowak/lab/order/exception/NotEnoughBalanceException.java
  src/main/java/camp/woowak/lab/order/exception/NotFoundMenuException.java
  src/main/java/camp/woowak/lab/order/exception/OrderErrorCode.java
  src/main/java/camp/woowak/lab/order/repository/.gitkeep
  src/main/java/camp/woowak/lab/order/repository/OrderRepository.java
  src/main/java/camp/woowak/lab/order/service/.gitkeep
  src/main/java/camp/woowak/lab/order/service/OrderCreationService.java
  src/main/java/camp/woowak/lab/order/service/command/OrderCreationCommand.java
  src/main/java/camp/woowak/lab/web/api/order/OrderApiController.java
  src/main/java/camp/woowak/lab/web/dto/response/order/OrderCreationResponse.java
  src/test/java/camp/woowak/lab/cart/domain/CartTest.java
  src/test/java/camp/woowak/lab/cart/service/CartServiceTest.java
  src/test/java/camp/woowak/lab/order/domain/OrderTest.java
  src/test/java/camp/woowak/lab/order/domain/SingleStoreOrderValidatorTest.java
  src/test/java/camp/woowak/lab/order/domain/WithdrawPointServiceTest.java
  src/test/java/camp/woowak/lab/order/service/OrderCreationServiceTest.java
  src/test/java/camp/woowak/lab/web/api/order/OrderApiControllerTest.java
Labels: ✨ Feature

#100 [feat] 전체 회원 조회
  src/main/java/camp/woowak/lab/customer/service/RetrieveCustomerService.java
  src/main/java/camp/woowak/lab/customer/service/dto/CustomerDTO.java
  src/main/java/camp/woowak/lab/vendor/service/RetrieveVendorService.java
  src/main/java/camp/woowak/lab/vendor/service/dto/VendorDTO.java
  src/main/java/camp/woowak/lab/web/api/customer/CustomerApiController.java
  src/main/java/camp/woowak/lab/web/api/vendor/VendorApiController.java
  src/main/java/camp/woowak/lab/web/dto/response/customer/RetrieveCustomerResponse.java
  src/main/java/camp/woowak/lab/web/dto/response/vendor/RetrieveVendorResponse.java
  src/test/java/camp/woowak/lab/customer/service/RetrieveCustomerServiceTest.java
  src/test/java/camp/woowak/lab/vendor/service/RetrieveVendorServiceTest.java
  src/test/java/camp/woowak/lab/web/api/customer/CustomerApiControllerTest.java
  src/test/java/camp/woowak/lab/web/api/vendor/VendorApiControllerTest.java
Labels: ✨ Feature

#93 [feat] 판매 금액 정산 - 모든 점주 및 OrderPayment 목록 조회, OrderPayment 상태 일괄 갱신
  src/main/java/camp/woowak/lab/menu/domain/Menu.java
  src/main/java/camp/woowak/lab/menu/domain/MenuValidator.java
  src/main/java/camp/woowak/lab/menu/exception/MenuErrorCode.java
  src/main/java/camp/woowak/lab/order/domain/vo/OrderItem.java
  src/main/java/camp/woowak/lab/payment/domain/OrderPayment.java
  src/main/java/camp/woowak/lab/payment/domain/OrderPaymentStatus.java
  src/main/java/camp/woowak/lab/payment/domain/PointPayment.java
  src/main/java/camp/woowak/lab/payment/repository/OrderPaymentRepository.java
  src/main/java/camp/woowak/lab/payment/service/OrderPaymentAdjustmentService.java
  src/main/java/camp/woowak/lab/store/service/command/MenuLineItem.java
  src/test/java/camp/woowak/lab/cart/domain/CartTest.java
  src/test/java/camp/woowak/lab/cart/service/CartServiceTest.java
  src/test/java/camp/woowak/lab/fixture/CartFixture.java
  src/test/java/camp/woowak/lab/menu/TestMenu.java
  src/test/java/camp/woowak/lab/menu/domain/MenuTest.java
  src/test/java/camp/woowak/lab/order/domain/WithdrawPointServiceTest.java
  src/test/java/camp/woowak/lab/store/service/StoreMenuRegistrationServiceTest.java
  src/test/java/camp/woowak/lab/web/api/cart/CartApiControllerTest.java
Labels: ✨ Feature

#94 [feat] 점주 주문 리스트 조회
  src/main/java/camp/woowak/lab/order/domain/Order.java
  src/main/java/camp/woowak/lab/order/domain/vo/OrderItem.java
  src/main/java/camp/woowak/lab/order/repository/OrderRepository.java
  src/main/java/camp/woowak/lab/order/service/RetrieveOrderListService.java
  src/main/java/camp/woowak/lab/order/service/command/RetrieveOrderListCommand.java
  src/main/java/camp/woowak/lab/order/service/dto/OrderDTO.java
  src/main/java/camp/woowak/lab/store/domain/Store.java
  src/main/java/camp/woowak/lab/store/domain/StoreAddress.java
  src/main/java/camp/woowak/lab/web/api/order/OrderApiController.java
  src/main/java/camp/woowak/lab/web/api/order/OrderExceptionHandler.java
  src/main/java/camp/woowak/lab/web/dto/response/order/RetrieveOrderListResponse.java
  src/test/java/camp/woowak/lab/cart/domain/CartTest.java
  src/test/java/camp/woowak/lab/fixture/StoreFixture.java
  src/test/java/camp/woowak/lab/fixture/VendorFixture.java
  src/test/java/camp/woowak/lab/order/repository/OrderRepositoryTest.java
  src/test/java/camp/woowak/lab/order/service/RetrieveOrderListServiceTest.java
  src/test/java/camp/woowak/lab/order/service/dto/TestOrderDTO.java
  src/test/java/camp/woowak/lab/web/api/order/OrderApiControllerTest.java
Labels: ✨ Feature

#102 [feat] 구매자는 매장 리스트를 조회할 수 있다
  src/main/java/camp/woowak/lab/order/domain/Order.java
  src/main/java/camp/woowak/lab/store/domain/StoreCategory.java
  src/main/java/camp/woowak/lab/web/api/store/StoreApiController.java
  src/main/java/camp/woowak/lab/web/dao/store/StoreDao.java
  src/main/java/camp/woowak/lab/web/dto/request/store/StoreFilterBy.java
  src/main/java/camp/woowak/lab/web/dto/request/store/StoreInfoListRequest.java
  src/main/java/camp/woowak/lab/web/dto/request/store/StoreInfoListRequestConst.java
  src/main/java/camp/woowak/lab/web/dto/request/store/StoreSortBy.java
  src/main/java/camp/woowak/lab/web/dto/response/store/StoreInfoListResponse.java
  src/test/java/camp/woowak/lab/web/api/store/StoreApiControllerTest.java
  src/test/java/camp/woowak/lab/web/api/store/StoreApiControllerWithDaoTest.java
  src/test/java/camp/woowak/lab/web/dao/store/StoreDaoTest.java
  src/test/java/camp/woowak/lab/web/dao/store/StoreDummiesFixture.java
  src/test/java/camp/woowak/lab/web/dto/response/store/StoreInfoListResponseTest.java
Labels: ✨ Feature

#107 [feat] 가게의 음식 상품 가격 수정
  src/main/java/camp/woowak/lab/menu/domain/Menu.java
  src/main/java/camp/woowak/lab/menu/exception/InvalidMenuPriceUpdateException.java
  src/main/java/camp/woowak/lab/menu/exception/MenuErrorCode.java
  src/main/java/camp/woowak/lab/menu/exception/MenuOwnerNotMatchException.java
  src/main/java/camp/woowak/lab/menu/service/MenuPriceUpdateService.java
  src/main/java/camp/woowak/lab/menu/service/command/MenuPriceUpdateCommand.java
  src/main/java/camp/woowak/lab/web/api/store/StoreApiController.java
  src/main/java/camp/woowak/lab/web/api/store/StoreExceptionHandler.java
  src/main/java/camp/woowak/lab/web/dto/request/store/MenuPriceUpdateRequest.java
  src/main/java/camp/woowak/lab/web/dto/response/store/MenuPriceUpdateResponse.java
  src/test/java/camp/woowak/lab/fixture/MenuFixture.java
  src/test/java/camp/woowak/lab/menu/domain/MenuTest.java
  src/test/java/camp/woowak/lab/menu/service/MenuPriceUpdateServiceTest.java
  src/test/java/camp/woowak/lab/web/api/store/StoreApiControllerTest.java
Labels: ✨ Feature

#106 [feat] 구매자 매장상세조회
  src/main/java/camp/woowak/lab/menu/domain/Menu.java
  src/main/java/camp/woowak/lab/menu/domain/MenuCategory.java
  src/main/java/camp/woowak/lab/menu/repository/MenuRepository.java
  src/main/java/camp/woowak/lab/order/service/dto/OrderDTO.java
  src/main/java/camp/woowak/lab/store/domain/Store.java
  src/main/java/camp/woowak/lab/store/domain/StoreAddress.java
  src/main/java/camp/woowak/lab/store/service/StoreDisplayService.java
  src/main/java/camp/woowak/lab/store/service/response/StoreDisplayResponse.java
  src/main/java/camp/woowak/lab/web/api/store/StoreApiController.java
  src/test/java/camp/woowak/lab/store/service/StoreDisplayServiceTest.java
  src/test/java/camp/woowak/lab/web/api/store/StoreApiControllerTest.java
Labels: ✨ Feature

#108 [feat] 음식 상품 수량 수정
  src/main/java/camp/woowak/lab/menu/exception/InvalidMenuStockUpdateException.java
  src/main/java/camp/woowak/lab/menu/exception/MenuErrorCode.java
  src/main/java/camp/woowak/lab/menu/exception/NotEqualsOwnerException.java
  src/main/java/camp/woowak/lab/menu/exception/NotUpdatableTimeException.java
  src/main/java/camp/woowak/lab/menu/repository/MenuRepository.java
  src/main/java/camp/woowak/lab/menu/service/UpdateMenuStockService.java
  src/main/java/camp/woowak/lab/menu/service/command/UpdateMenuStockCommand.java
  src/main/java/camp/woowak/lab/web/api/menu/MenuApiController.java
  src/main/java/camp/woowak/lab/web/api/menu/MenuExceptionHandler.java
  src/main/java/camp/woowak/lab/web/dto/request/menu/UpdateMenuStockRequest.java
  src/main/java/camp/woowak/lab/web/dto/response/menu/UpdateMenuStockResponse.java
  src/test/java/camp/woowak/lab/menu/service/UpdateMenuStockServiceTest.java
  src/test/java/camp/woowak/lab/web/api/menu/MenuApiControllerTest.java
Labels: ✨ Feature

#117 [fix] Store 도메인의 isopen 메서드 오류 수정
  src/main/java/camp/woowak/lab/store/domain/StoreTime.java
  src/test/java/camp/woowak/lab/store/domain/StoreTest.java
Labels: 🐞 BugFix

#112 [feat] 메뉴 카테고리를 조회할 수 있다
  src/main/java/camp/woowak/lab/web/api/store/StoreApiController.java
  src/main/java/camp/woowak/lab/web/dao/.gitkeep
  src/main/java/camp/woowak/lab/web/dao/MenuDao.java
  src/main/java/camp/woowak/lab/web/dao/QueryDslMenuDao.java
  src/main/java/camp/woowak/lab/web/dto/response/store/MenuCategoryResponse.java
  src/test/java/camp/woowak/lab/web/api/store/StoreApiControllerTest.java
  src/test/java/camp/woowak/lab/web/dao/QueryDslMenuDaoTest.java
Labels: ✨ Feature

#115 [feat] 점주는 페이지별 주문 리스트를 조회할 수 있다
  src/main/java/camp/woowak/lab/order/repository/OrderRepository.java
  src/main/java/camp/woowak/lab/order/service/RetrieveOrderListService.java
  src/main/java/camp/woowak/lab/order/service/command/RetrieveOrderListCommand.java
  src/main/java/camp/woowak/lab/web/api/order/OrderApiController.java
  src/test/java/camp/woowak/lab/order/repository/OrderRepositoryTest.java
  src/test/java/camp/woowak/lab/order/service/RetrieveOrderListServiceTest.java
  src/test/java/camp/woowak/lab/web/api/order/OrderApiControllerTest.java
Labels: ✨ Feature

#120 [feat] 주문/결재시 카트를 비운다
  src/main/java/camp/woowak/lab/order/service/OrderCreationService.java
Labels: 🐞 BugFix

#122 [fix] store 도메인의 isOpen 메서드 수정 못했던것 수정
  src/main/java/camp/woowak/lab/store/domain/Store.java
Labels: 🐞 BugFix

#131 [feat] redis 테스트 환경 구축
  .github/workflows/build.yml
  build.gradle
  src/test/java/camp/woowak/lab/container/ContainerSettingTest.java
  src/test/resources/application.yml
Labels: 📃 Docs, ✨ Feature

#134 [feat] redis를 이용하여 cart를 저장/조회/삭제하도록 구현
  src/main/java/camp/woowak/lab/cart/domain/Cart.java
  src/main/java/camp/woowak/lab/cart/persistence/redis/entity/RedisCartEntity.java
  src/main/java/camp/woowak/lab/cart/persistence/redis/entity/RedisCartItemEntity.java
  src/main/java/camp/woowak/lab/cart/persistence/redis/repository/RedisCartRepository.java
  src/main/java/camp/woowak/lab/cart/repository/InMemoryCartRepository.java
  src/main/java/camp/woowak/lab/cart/service/CartService.java
  src/main/java/camp/woowak/lab/infra/config/RedisConfiguration.java
  src/main/resources/application.yaml
  src/test/java/camp/woowak/lab/cart/persistence/redis/repository/RedisCartRepositoryTest.java
  src/test/java/camp/woowak/lab/container/ContainerSettingTest.java
Labels: ✨ Feature, 💪 Improve

#133 [feat] Cart를 DB에 저장한다
  src/main/java/camp/woowak/lab/cart/domain/Cart.java
  src/main/java/camp/woowak/lab/cart/domain/vo/CartItem.java
  src/main/java/camp/woowak/lab/cart/persistence/jpa/entity/CartEntity.java
  src/main/java/camp/woowak/lab/cart/persistence/jpa/entity/CartItemEntity.java
  src/main/java/camp/woowak/lab/cart/persistence/jpa/repository/CartEntityRepository.java
  src/main/java/camp/woowak/lab/cart/persistence/jpa/repository/JpaCartRepository.java
  src/main/java/camp/woowak/lab/cart/service/CartService.java
  src/test/java/camp/woowak/lab/cart/persistence/jpa/repository/JpaCartRepositoryTest.java
Labels: ✨ Feature, 💪 Improve

#135 [feat] 카트를 조회할 수 있는 Dao를 Redis를 이용해서 구현
  src/main/java/camp/woowak/lab/web/dao/cart/RedisCartDao.java
  src/main/java/camp/woowak/lab/web/dto/response/CartResponse.java
  src/test/java/camp/woowak/lab/web/dao/cart/RedisCartDaoTest.java
  src/test/java/camp/woowak/lab/web/dao/store/StoreDummiesFixture.java
Labels: ✨ Feature, 💪 Improve

#137 [feat] 구매자는 카트를 조회할 수 있다
  src/main/java/camp/woowak/lab/cart/exception/CartErrorCode.java
  src/main/java/camp/woowak/lab/cart/exception/NotFoundCartException.java
  src/main/java/camp/woowak/lab/web/api/cart/CartApiController.java
  src/main/java/camp/woowak/lab/web/dao/cart/CartDao.java
  src/main/java/camp/woowak/lab/web/dao/cart/JpaCartDao.java
  src/main/java/camp/woowak/lab/web/dao/cart/RedisCartDao.java
  src/main/java/camp/woowak/lab/web/dto/response/CartResponse.java
  src/test/java/camp/woowak/lab/web/dao/cart/RedisCartDaoTest.java
  src/test/java/camp/woowak/lab/web/dao/store/StoreDummiesFixture.java
Labels: ✨ Feature, 💪 Improve

#139 [feat] 화면 구현
  src/main/java/camp/woowak/lab/cart/service/CartService.java
  src/main/java/camp/woowak/lab/web/api/cart/CartApiController.java
  src/main/java/camp/woowak/lab/web/dto/response/cart/CartResponse.java
  src/main/java/camp/woowak/lab/web/view/ViewController.java
  src/main/resources/templates/login.html
  src/main/resources/templates/store.html
  src/main/resources/templates/stores.html
Labels: ✨ Feature

#130 [feat] 점주는 주문 리스트를 필터링할 수 있다
  src/main/java/camp/woowak/lab/order/service/RetrieveOrderListService.java
  src/main/java/camp/woowak/lab/order/service/command/RetrieveOrderListCommand.java
  src/main/java/camp/woowak/lab/web/api/order/OrderApiController.java
  src/main/java/camp/woowak/lab/web/api/store/StoreApiController.java
  src/main/java/camp/woowak/lab/web/dao/menu/MenuDao.java
  src/main/java/camp/woowak/lab/web/dao/menu/QueryDslMenuDao.java
  src/main/java/camp/woowak/lab/web/dao/order/OrderDao.java
  src/main/java/camp/woowak/lab/web/dao/order/OrderQuery.java
  src/main/java/camp/woowak/lab/web/dao/order/QueryDslOrderDao.java
  src/main/java/camp/woowak/lab/web/dto/request/SignUpVendorRequest.java
  src/main/java/camp/woowak/lab/web/dto/response/order/OrderResponse.java
  src/test/java/camp/woowak/lab/order/service/RetrieveOrderListServiceTest.java
  src/test/java/camp/woowak/lab/web/api/store/StoreApiControllerTest.java
  src/test/java/camp/woowak/lab/web/dao/menu/QueryDslMenuDaoTest.java
  src/test/java/camp/woowak/lab/web/dao/order/QueryDslOrderDaoTest.java
Labels: ✨ Feature

#148 [feat] 주문 시점에 배타락을 적용해서 문제를 해결
  src/main/java/camp/woowak/lab/cart/persistence/jpa/repository/CartEntityRepository.java
  src/test/java/camp/woowak/lab/cart/persistence/jpa/repository/JpaCartRepositoryTest.java
Labels: ✨ Feature, 💪 Improve

#147 [feat] 주문 시점에 분산락을 적용해서 문제를 해결한 버전
  build.gradle
  src/main/java/camp/woowak/lab/cart/persistence/redis/entity/RedisCartEntity.java
  src/main/java/camp/woowak/lab/infra/aop/AopForTransaction.java
  src/main/java/camp/woowak/lab/infra/aop/CustomSpringELParser.java
  src/main/java/camp/woowak/lab/infra/aop/DistributedLock.java
  src/main/java/camp/woowak/lab/infra/aop/DistributedLockAop.java
  src/main/java/camp/woowak/lab/infra/config/RedisConfiguration.java
  src/main/java/camp/woowak/lab/infra/config/RedissonConfiguration.java
  src/main/java/camp/woowak/lab/order/service/OrderCreationService.java
Labels: ✨ Feature, 💪 Improve

#152 [fix] 테스트 환경의 Redis를 test-container 에서 embedded-redis로 변경 후 junit 테스트 실행 시 실행될 수 있도록 수정
  build.gradle
  src/test/java/camp/woowak/lab/container/ContainerSettingTest.java
  src/test/java/camp/woowak/lab/helper/EmbeddedRedisExtension.java
  src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
  src/test/resources/junit-platform.properties
Labels: 🔨 Refactor, ✅ Test

#140 [feat] 할인 쿠폰 분산락 적용
  build.gradle
  src/main/java/camp/woowak/lab/coupon/repository/CouponRepository.java
  src/main/java/camp/woowak/lab/coupon/service/IssueCouponService.java
  src/main/java/camp/woowak/lab/infra/aop/AopForTransaction.java
  src/main/java/camp/woowak/lab/infra/aop/CustomSpringELParser.java
  src/main/java/camp/woowak/lab/infra/aop/DistributedLock.java
  src/main/java/camp/woowak/lab/infra/aop/DistributedLockAop.java
  src/main/java/camp/woowak/lab/infra/config/RedissonConfiguration.java
  src/main/java/camp/woowak/lab/web/api/coupon/CouponApiController.java
  src/main/resources/application.yaml
  src/test/java/camp/woowak/lab/container/ContainerSettingTest.java
  src/test/java/camp/woowak/lab/infra/aop/DistributedLockAopTest.java
  src/test/java/camp/woowak/lab/web/api/coupon/CouponApiControllerTest.java
  src/test/resources/application.yml
Labels: 💪 Improve

#145 [feat] 음식 상품 재고수 Redis 캐싱
  build.gradle
  src/main/java/camp/woowak/lab/cart/service/CartService.java
  src/main/java/camp/woowak/lab/infra/cache/MenuStockCacheService.java
  src/main/java/camp/woowak/lab/infra/cache/exception/CacheMissException.java
  src/main/java/camp/woowak/lab/infra/cache/exception/RedisLockAcquisitionException.java
  src/main/java/camp/woowak/lab/infra/cache/redis/RedisCacheConstants.java
  src/main/java/camp/woowak/lab/infra/cache/redis/RedisMenuStockCacheService.java
  src/main/java/camp/woowak/lab/infra/config/RedisConfiguration.java
  src/main/java/camp/woowak/lab/infra/config/RedissonConfiguration.java
  src/main/java/camp/woowak/lab/menu/repository/MenuRepository.java
  src/main/java/camp/woowak/lab/order/domain/Order.java
  src/main/java/camp/woowak/lab/order/domain/StockRequester.java
  src/main/resources/application.yaml
  src/test/java/camp/woowak/lab/infra/cache/FakeMenuStockCacheService.java
  src/test/java/camp/woowak/lab/infra/cache/RedisMenuStockCacheServiceTest.java
  src/test/java/camp/woowak/lab/infra/cache/RedissonTest.java
  src/test/java/camp/woowak/lab/order/domain/OrderTest.java
  src/test/java/camp/woowak/lab/order/domain/StockRequesterTest.java
  src/test/java/camp/woowak/lab/order/repository/OrderRepositoryTest.java
  src/test/java/camp/woowak/lab/order/service/OrderConcurrencyIntegrationTest.java
  src/test/java/camp/woowak/lab/order/service/OrderCreationServiceTest.java
  src/test/java/camp/woowak/lab/web/api/store/StoreApiControllerWithDaoTest.java
  src/test/java/camp/woowak/lab/web/dao/store/StoreDummiesFixture.java
Labels: 💪 Improve

#155 [feat] 멱등성키 적용을 통한 중복결제 방지
  src/main/java/camp/woowak/lab/infra/aop/idempotent/Idempotent.java
  src/main/java/camp/woowak/lab/infra/aop/idempotent/IdempotentAop.java
  src/main/java/camp/woowak/lab/infra/aop/idempotent/exception/IdempotencyKeyErrorCode.java
  src/main/java/camp/woowak/lab/infra/aop/idempotent/exception/IdempotencyKeyNotExistsException.java
  src/main/java/camp/woowak/lab/order/exception/CompletedOrderException.java
  src/main/java/camp/woowak/lab/order/exception/OrderErrorCode.java
  src/main/java/camp/woowak/lab/web/api/order/OrderApiController.java
  src/main/resources/templates/store.html
  src/test/java/camp/woowak/lab/web/api/order/OrderApiControllerAOPTest.java
Labels: ✨ Feature, 💪 Improve
